on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install signing key
        run: |
          sudo mkdir -p /etc/nix
          echo "$NIX_SIGNING_KEY" | sudo tee /etc/nix/key.sec > /dev/null
          sudo chmod 0600 /etc/nix/key.sec
        env:
          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: secret-key-files = /etc/nix/key.sec

      - run: nix copy .#packages.x86_64-linux.ps2dev --to "s3://ps-nix-cache?endpoint=${{ vars.S3_ENDPOINT }}&compression=zstd"
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
